Selenium_WebElements and locators_01
NadiaKalnyk/home.tasks pull request #11
Opened 2022-12-26 20:42 UTC by NadiaKalnyk

2022-12-27 20:41 UTC, Protesiani requested changes

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/Checkboxes.java
> +        }
рядки з 18 по 34
виглядає громіздко та багато повторень
як щодо більш універсального варіанту:
```
List<WebElement> checkboxes = driver.findElements(By.xpath("//*[@id='checkboxes']/input"));
for(int i = 0; i < checkboxes.size(); i++)
    System.out.println("Checkbox #" + i + " is " + (checkboxes.get(i).isSelected() ? "selected" : "unselected"));
```
можна за бажанням написати ("Checkbox #" + i+1 + " is ".... , тоді нумерація буде з 1, а не з 0

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/Checkboxes.java
> +        driver.findElement(By.xpath("//*[@id='checkboxes']/input[2]"));
тест ніяк не знає стан чекбоксів на початку, тому клік тільки по першому не гарантує що будуть вибрані обидва

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/ClickOnButtonSelectElem.java
> +    final int collectionSize = 11;
можна доручити підрахунок кількості рядків у таблиці самому тесту, а не робити це вручну

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/ClickOnButtonSelectElem.java
> +    final int collectionSize = 11;
ну і так можна дуже легко заплутатись, бо елементів все ж 10
просто в циклі for треба було написати i <= collectionSize

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/ClickOnButtonSelectElem.java
> +        driver.findElement(cssSelector("[id='323823e0-677f-013b-9e37-5efda14eb2e0']")).click();
тут формально все правильно. Але ця айдішка генерується сторінкою рандомно, і буде кожен раз нова, тому тест буде видавати помилку на цьому місці

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/Login.java
> +        driver.findElement(cssSelector(".success")).getText().compareTo("You logged into a secure area!");
треба замінити compareTo на Assert.assertEquals

2022-12-27 20:41 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/Login.java
> +        driver.quit();
"на подумати": як зробити, щоб браузер закривався і в випадку коли ассерт зафейлився? Які фічі TestNG можуть допомогти?

2022-12-27 22:25 UTC, NadiaKalnyk commented on src/test/java/ua/hillel/tests/seleniumLocators/ClickOnButtonSelectElem.java
> +        driver.findElement(cssSelector("[id='323823e0-677f-013b-9e37-5efda14eb2e0']")).click();
як можна знайти цей елемент по-іншому? я пробувала через клас, але так теж не виходить - він один і загальний - 'button'

2022-12-27 22:27 UTC, NadiaKalnyk commented on src/test/java/ua/hillel/tests/seleniumLocators/Checkboxes.java
> +        }
дякую за ідею! це значно скоротило код

2022-12-27 22:27 UTC, NadiaKalnyk commented on src/test/java/ua/hillel/tests/seleniumLocators/Checkboxes.java
> +        driver.findElement(By.xpath("//*[@id='checkboxes']/input[2]"));
Виправила. дякую

2022-12-27 22:45 UTC, NadiaKalnyk commented on src/test/java/ua/hillel/tests/seleniumLocators/Login.java
> +        driver.quit();
анотація @AfterTest. я пробувала з нею, але не получилося..

2022-12-28 09:15 UTC, Protesiani commented on src/test/java/ua/hillel/tests/seleniumLocators/ClickOnButtonSelectElem.java
> +        driver.findElement(cssSelector("[id='323823e0-677f-013b-9e37-5efda14eb2e0']")).click();
вибирай на свій смак:
		By.cssSelector("div a:nth-of-type(1).button")
		By.xpath("//a[@class = 'button']")
		By.xpath("//div[@class='large-2 columns']/a[1]")

2023-01-05 15:44 UTC, Protesiani approved these changes

2023-01-20 08:50 UTC, merged