file without changes
NadiaKalnyk/home.tasks pull request #15
Opened 2023-01-08 14:20 UTC by NadiaKalnyk

2023-01-08 21:28 UTC, Protesiani requested changes
перед комітом перевір що файл дійсно змінюється і що тест можна проранити декілька разів підряд

2023-01-08 21:28 UTC, Protesiani commented on src/main/java/ua/hillel/homeTask_16_17/TheInternetSite/UploadPage.java
> +        Assert.assertTrue(successMessage.getText().contains("File Uploaded!"));
Assert'и мають бути в тесті, а не в коді PageObject

2023-01-08 21:28 UTC, Protesiani commented on src/main/java/ua/hillel/homeTask_16_17/TheInternetSite/UploadPage.java
> +        chooseButton.sendKeys((CharSequence) filesInFolder[0].getAbsolutePath());
filesInFolder[0] - трохи ризикований і наївний спосіб, але ок

2023-01-08 21:28 UTC, Protesiani commented on src/main/java/ua/hillel/homeTask_16_17/WorkWithFiles/FileModification.java
> +    public void changeFile() throws IOException {
цей метод не викликається

2023-01-08 21:28 UTC, Protesiani commented on src/test/java/ua/hillel/tests/files/Files.java
> +    @Test
судячи з завдання, це має бути один тест

2023-01-08 21:28 UTC, Protesiani commented on src/main/java/ua/hillel/homeTask_16_17/WorkWithFiles/FileModification.java
> +        String text = "This file was changed";
у завданні сказано декілька рядків

2023-01-09 15:05 UTC, NadiaKalnyk commented on src/main/java/ua/hillel/homeTask_16_17/WorkWithFiles/FileModification.java
> +    public void changeFile() throws IOException {
![image](https://user-images.githubusercontent.com/117226153/211339627-8b08391f-9281-43a5-86f9-99f2d1619b5f.png)
тепер правильно?

2023-01-09 15:38 UTC, NadiaKalnyk commented on src/test/java/ua/hillel/tests/files/Files.java
> +    @Test
я не думала, що це буде помилкою. 
ок, я зміню на один тест

2023-01-10 19:43 UTC, NadiaKalnyk commented on src/main/java/ua/hillel/homeTask_16_17/TheInternetSite/UploadPage.java
> +        chooseButton.sendKeys((CharSequence) filesInFolder[0].getAbsolutePath());
замінила циклом for-each

2023-01-16 08:58 UTC, merged