REST_01
NadiaKalnyk/home.tasks pull request #17
Opened 2023-01-17 06:55 UTC by NadiaKalnyk

returnByStatus gets code 404

2023-01-17 09:24 UTC, apollyonix requested changes
Оскільки це тести, то бажано б ще додати тестові перевірки. Можемо перевіряти відповідь від API:
- для inventory можна сторити просту перевірку, що отримали 200 ок
- для створення нового ордеру - що у відповіді отримали ті ж самі дані, які були відправлені (водповідно, все збережено коректно на стороні сервісу)

2023-01-18 19:07 UTC, NadiaKalnyk commented
@apollyonix дякую за коментар.
для створення нового ордеру в тесті placeNewOrderStoreWithGSON() - добавила перевірку  даних, а в placeNewOrderInStore() - не получилося  з перевіркою даних, то там перевірка, що статус 200 ок

2023-01-19 11:02 UTC, MaximKarpenko approved these changes

2023-01-19 11:03 UTC, apollyonix approved these changes

2023-01-20 08:34 UTC, merged